services:
  mysql:
    image: mysql:8.4
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
  pgsql:
    image: postgres:15.10
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
